### ISSUE TITLE
Unable to remove item from list

### ISSUE THREAD

**Issue by wesleyfranks** [IronFuturist/todo24#1]
java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.remove(Collections.java:1105)
        at com.wesleyfranks.todo24.ui.create.CreateFragment.OnRadioButtonChecked(CreateFragment.kt:110)
        at com.wesleyfranks.todo24.data.TodoAdapter$ViewHolder$bind$2.onClick(TodoAdapter.kt:50)

**Comment by wesleyfranks** [comment]
I was able to fix this by "cloning" the list as Brady suggested. I did some research and found that you can do the following:

updatedList = adapter.currentList.stream().collect(Collectors.toList());

This allowed me to do what I need to do. I also just focused on the single source of truth and only create, edit, update, delete from the database to make it easier to code in the infrastructure.

Gotta admit my analytical brain loves using issues more so. I can keep track of things (never used issues or PRs before).
